name: cat_holder
description: SelfTable assessment.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/awesome_cat.png
    - assets/bad_cat.jpeg
    - assets/cursed_cat.jpeg
    - assets/not_a_cat.jpg
    - assets/regular_cat.jpg
