// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvRbKqRfFK5-UlTiaFx55SzjnHvwum4zo',
    appId: '1:14278167469:web:44088834a6a7e67024ef24',
    messagingSenderId: '14278167469',
    projectId: 'catholder-a0a4b',
    authDomain: 'catholder-a0a4b.firebaseapp.com',
    storageBucket: 'catholder-a0a4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4d9LqmrU18HNsPFtOKHimHr9CDNF_eU',
    appId: '1:14278167469:android:87c062cb70e363aa24ef24',
    messagingSenderId: '14278167469',
    projectId: 'catholder-a0a4b',
    storageBucket: 'catholder-a0a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL-YNtdX4w289FyZ1CvnBlSUzet--rBNk',
    appId: '1:14278167469:ios:b22c0e945c30e79e24ef24',
    messagingSenderId: '14278167469',
    projectId: 'catholder-a0a4b',
    storageBucket: 'catholder-a0a4b.appspot.com',
    iosClientId: '14278167469-o7rc0h2099i8qesie2b263mmohi27l6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.catHolder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL-YNtdX4w289FyZ1CvnBlSUzet--rBNk',
    appId: '1:14278167469:ios:b22c0e945c30e79e24ef24',
    messagingSenderId: '14278167469',
    projectId: 'catholder-a0a4b',
    storageBucket: 'catholder-a0a4b.appspot.com',
    iosClientId: '14278167469-o7rc0h2099i8qesie2b263mmohi27l6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.catHolder',
  );
}
